//! `INSERT INTO .. VALUES ..`, using the `Defaultable<T>` design from the
//! plan: a NOT NULL + has-default column gets a Rust field of
//! `Defaultable<T>` so "omit" (apply the schema default) and "explicit
//! value" are distinguishable — and, unlike `Option<T>`, a nullable column
//! with a default gets `Defaultable<Option<T>>` so "omit", "explicit
//! NULL", and "explicit value" are all three distinguishable. Every row in
//! one `INSERT` shares the same column list (from `InsertRow::COLUMNS`);
//! a `Defaultable::Default` field renders as the literal `DEFAULT` keyword
//! in that row's `VALUES (..)` tuple rather than changing the column list,
//! so rows with different omitted fields can still share one statement.

use std::marker::PhantomData;

use crate::dialect::{Dialect, SupportsOnConflict, SupportsReturning};
use crate::expr::{Column, ExprKind, SqlType, Value};
use crate::render::{render_expr, render_ident};
use crate::scope::{Cons, Nil, NotNull, Table, TableSlot};
use crate::select::Selection;
use crate::update::UpdateRow;

#[derive(Debug, Clone, PartialEq, Default)]
pub enum Defaultable<T> {
    #[default]
    Default,
    Value(T),
}

impl<T> Defaultable<T> {
    pub fn value(v: T) -> Self {
        Defaultable::Value(v)
    }
}

#[derive(Debug, Clone)]
pub enum InsertValue {
    Value(Value),
    /// Renders as the bare `DEFAULT` keyword in the `VALUES` list.
    Default,
}

impl<T: Into<Value>> From<Defaultable<T>> for InsertValue {
    fn from(d: Defaultable<T>) -> Self {
        match d {
            Defaultable::Default => InsertValue::Default,
            Defaultable::Value(v) => InsertValue::Value(v.into()),
        }
    }
}

/// Implemented by the `#[derive(Table)]`-generated `*Insert` struct for
/// each table. `COLUMNS` and `values()` must agree on both order and
/// length — the macro generates both from the same field list, so this
/// invariant never has to be hand-maintained.
pub trait InsertRow {
    type Table: Table;
    const COLUMNS: &'static [&'static str];
    fn into_values(self) -> Vec<InsertValue>;
}

/// A statically-checked `ON CONFLICT` target: one or more columns proven
/// (via the `T` parameter) to actually belong to the table being inserted
/// into — a raw `&[&str]` column-name list would let a typo or a
/// wrong-table column compile and only fail against the real database.
/// Implemented for a bare `Column<T, S>` (single-column unique constraint)
/// and tuples of up to three (composite unique constraints); add more
/// tuple arities if a real schema needs them.
pub trait ConflictTarget<T: Table> {
    fn column_names(&self) -> Vec<&'static str>;
}

impl<T: Table, S: SqlType> ConflictTarget<T> for Column<T, S> {
    fn column_names(&self) -> Vec<&'static str> {
        vec![self.name]
    }
}

impl<T: Table, A: ConflictTarget<T>> ConflictTarget<T> for (A,) {
    fn column_names(&self) -> Vec<&'static str> {
        self.0.column_names()
    }
}

impl<T: Table, A: ConflictTarget<T>, B: ConflictTarget<T>> ConflictTarget<T> for (A, B) {
    fn column_names(&self) -> Vec<&'static str> {
        let mut v = self.0.column_names();
        v.extend(self.1.column_names());
        v
    }
}

impl<T: Table, A: ConflictTarget<T>, B: ConflictTarget<T>, C: ConflictTarget<T>> ConflictTarget<T>
    for (A, B, C)
{
    fn column_names(&self) -> Vec<&'static str> {
        let mut v = self.0.column_names();
        v.extend(self.1.column_names());
        v.extend(self.2.column_names());
        v
    }
}

enum ConflictAction {
    DoNothing,
    /// Reuses `UpdateRow` (the same trait `UPDATE ... SET` uses) rather
    /// than a separate "conflict set" representation — a `*Update` struct
    /// generated by `#[derive(Table)]` already computes exactly the
    /// `(column, value)` pairs this needs, so `.on_conflict_do_update(..)`
    /// takes the same kind of value `.set(..)` does.
    ///
    /// **Known limitation**: this only supports setting literal/bound
    /// values, not referencing `EXCLUDED.column` (Postgres's "the value
    /// that would have been inserted") — a real, useful upsert pattern
    /// (`SET total = users.total + EXCLUDED.total`) that needs its own
    /// typed API design, deferred rather than half-supported via a stringy
    /// escape hatch.
    DoUpdate(Vec<(&'static str, Value)>),
}

struct ConflictClause {
    target: Vec<&'static str>,
    action: ConflictAction,
}

fn render_conflict_clause<D: Dialect>(
    clause: &ConflictClause,
    sql: &mut String,
    params: &mut Vec<Value>,
) {
    sql.push_str(" ON CONFLICT (");
    for (i, c) in clause.target.iter().enumerate() {
        if i > 0 {
            sql.push_str(", ");
        }
        render_ident::<D>(sql, c);
    }
    sql.push(')');
    match &clause.action {
        ConflictAction::DoNothing => sql.push_str(" DO NOTHING"),
        ConflictAction::DoUpdate(sets) => {
            sql.push_str(" DO UPDATE SET ");
            for (i, (col, val)) in sets.iter().enumerate() {
                if i > 0 {
                    sql.push_str(", ");
                }
                render_ident::<D>(sql, col);
                sql.push_str(" = ");
                params.push(val.clone());
                sql.push_str(&D::placeholder(params.len()));
            }
        }
    }
}

pub struct InsertSeed<D, T> {
    _marker: PhantomData<fn() -> (D, T)>,
}

pub fn insert<D, T: Table>(_table: T) -> InsertSeed<D, T> {
    InsertSeed {
        _marker: PhantomData,
    }
}

impl<D, T: Table> InsertSeed<D, T> {
    pub fn values<R: InsertRow<Table = T>>(self, row: R) -> Insert<D, T, R> {
        Insert {
            rows: vec![row.into_values()],
            on_conflict: None,
            _marker: PhantomData,
        }
    }
}

fn render_values_clause<D: Dialect, T: Table, R: InsertRow<Table = T>>(
    rows: &[Vec<InsertValue>],
    on_conflict: &Option<ConflictClause>,
) -> (String, Vec<Value>) {
    let mut sql = String::from("INSERT INTO ");
    render_ident::<D>(&mut sql, T::NAME);
    sql.push_str(" (");
    for (i, c) in R::COLUMNS.iter().enumerate() {
        if i > 0 {
            sql.push_str(", ");
        }
        render_ident::<D>(&mut sql, c);
    }
    sql.push_str(") VALUES ");

    let mut params = Vec::new();
    for (row_i, row) in rows.iter().enumerate() {
        if row_i > 0 {
            sql.push_str(", ");
        }
        sql.push('(');
        for (i, v) in row.iter().enumerate() {
            if i > 0 {
                sql.push_str(", ");
            }
            match v {
                InsertValue::Default => sql.push_str("DEFAULT"),
                InsertValue::Value(v) => {
                    params.push(v.clone());
                    sql.push_str(&D::placeholder(params.len()));
                }
            }
        }
        sql.push(')');
    }

    if let Some(clause) = on_conflict {
        render_conflict_clause::<D>(clause, &mut sql, &mut params);
    }

    (sql, params)
}

pub struct Insert<D, T: Table, R: InsertRow<Table = T>> {
    rows: Vec<Vec<InsertValue>>,
    on_conflict: Option<ConflictClause>,
    _marker: PhantomData<fn() -> (D, T, R)>,
}

impl<D, T: Table, R: InsertRow<Table = T>> Insert<D, T, R> {
    /// Bulk insert: add another row to the same statement.
    pub fn values(mut self, row: R) -> Self {
        self.rows.push(row.into_values());
        self
    }
}

impl<D: SupportsOnConflict, T: Table, R: InsertRow<Table = T>> Insert<D, T, R> {
    /// `ON CONFLICT (..) DO NOTHING` — only exists on dialects with
    /// `SupportsOnConflict` (Postgres, SQLite); MySQL's equivalent is the
    /// differently-shaped `ON DUPLICATE KEY UPDATE`, its own future API.
    pub fn on_conflict_do_nothing(mut self, target: impl ConflictTarget<T>) -> Self {
        self.on_conflict = Some(ConflictClause {
            target: target.column_names(),
            action: ConflictAction::DoNothing,
        });
        self
    }

    /// `ON CONFLICT (..) DO UPDATE SET ..`, reusing the same `*Update`
    /// struct `.set(..)` on `update()` takes — see `ConflictAction`'s doc
    /// comment for what this does and doesn't support yet.
    pub fn on_conflict_do_update<U: UpdateRow<Table = T>>(
        mut self,
        target: impl ConflictTarget<T>,
        set: U,
    ) -> Self {
        self.on_conflict = Some(ConflictClause {
            target: target.column_names(),
            action: ConflictAction::DoUpdate(set.sets()),
        });
        self
    }
}

impl<D: Dialect, T: Table, R: InsertRow<Table = T>> Insert<D, T, R> {
    pub fn to_sql(&self) -> (String, Vec<Value>) {
        render_values_clause::<D, T, R>(&self.rows, &self.on_conflict)
    }
}

impl<D: SupportsReturning, T: Table, R: InsertRow<Table = T>> Insert<D, T, R> {
    /// `RETURNING` only exists on dialects with `SupportsReturning`
    /// (Postgres, later SQLite) — calling this on a MySQL-backed `Insert`
    /// is a compile error, not a documented gap.
    ///
    /// This returns a *different type* (`InsertReturning`), not `Self` with
    /// a field toggled — an earlier draft tried to keep one `Insert` struct
    /// with an `Option<Vec<ExprKind>>` returning field, but that throws away
    /// `Sel`'s concrete type, which the execution layer needs to know what
    /// to decode a returned row *into*. Encoding "has returning or not" as
    /// two distinct struct types (rather than one type with an erased
    /// optional field) is also what avoids ever needing a blanket impl
    /// bounded by "if the type parameter happens to implement X" — the
    /// exact family of coherence trap the Phase 0 spike already hit once
    /// (see `scope::WrapNullable`'s doc comment).
    pub fn returning<Sel, Idx>(self, sel: Sel) -> InsertReturning<D, T, R, Sel>
    where
        Sel: Selection<Cons<TableSlot<T, NotNull>, Nil>, Idx>,
    {
        InsertReturning {
            rows: self.rows,
            on_conflict: self.on_conflict,
            returning_exprs: sel.exprs(),
            _marker: PhantomData,
        }
    }
}

/// An `INSERT .. RETURNING ..` statement. `Sel`'s concrete type is retained
/// (unlike a hypothetical `Option<Vec<ExprKind>>` field on `Insert` itself)
/// specifically so the execution layer can decode returned rows into
/// `Sel::Output` — see `Insert::returning`'s doc comment.
pub struct InsertReturning<D, T: Table, R: InsertRow<Table = T>, Sel> {
    rows: Vec<Vec<InsertValue>>,
    on_conflict: Option<ConflictClause>,
    returning_exprs: Vec<ExprKind>,
    _marker: PhantomData<fn() -> (D, T, R, Sel)>,
}

impl<D: Dialect, T: Table, R: InsertRow<Table = T>, Sel> InsertReturning<D, T, R, Sel> {
    pub fn to_sql(&self) -> (String, Vec<Value>) {
        let (mut sql, mut params) = render_values_clause::<D, T, R>(&self.rows, &self.on_conflict);
        sql.push_str(" RETURNING ");
        for (i, e) in self.returning_exprs.iter().enumerate() {
            if i > 0 {
                sql.push_str(", ");
            }
            render_expr::<D>(e, &mut sql, &mut params);
        }
        (sql, params)
    }
}
